# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFG4XIHo-PBP9IqNaPKr9LFAOClk0Y01
"""

import numpy as np
import pandas as pd

df = pd.read_excel( "/content/Students Dataset.xlsx")

df.head(20)

df.tail()

df.info()

df.describe()

df.describe(include=object)

df.describe(include='all')

df['deg_yop'].unique()

df['course'].nunique()

df.value_counts()

df['Type'].value_counts()

df.shape

df.shape[0]

df.shape[1]

df.size

df.dtypes

df.ndim

df.values

df.T

df.columns

df.sample()

df.sample(3)

df.sample(frac=0.3)

df.sort_values(by = ['Name','10_per'])

df.sort_index()

df.loc[3,'Type']

df.loc[3:8,'Type':'deg_yop']

df.iloc[8,4]

df.iloc[1:7,2:8]

