# -*- coding: utf-8 -*-
"""Numpy Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHBrX5LF-lsbJLjw_UKbRakoIzYABcHd
"""

import numpy as np

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
print("5. Mean")
print("6. Variance")
print("7. Standard Deviation")

choice = int(input("Enter your choice: "))

if choice == 1:
    print("Result =", np.add(a, b))

elif choice == 2:
    print("Result =", np.subtract(a, b))

elif choice == 3:
    print("Result =", np.multiply(a, b))

elif choice == 4:
    print("Result =", np.divide(a, b))

elif choice == 5:
    print("Result =", np.mean([a,b]))

elif choice == 6:
     print ("Result =",np.var([a,b]))

elif choice == 7:
     print("Result =", np.std([a,b]))

else:
    print("Invalid Choice")

