# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaGMGeTAnEhUhWPUMpHDbC08QrX1ZfTP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.load_dataset('tips')

styles = ['white','dark','whitegrid','darkgrid','ticks']
context = ['poster','paper','talk','notebook']
for i in context:
    for j in styles:

        sns.set_context(i)
        sns.set_style(j)
        plt.plot(np.arange(1,10),np.arange(1,10))
        plt.title(f'style : {j} and context : {i}')
        plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('tips')

df.columns

sns.histplot(data=df,x='total_bill',hue='smoker',bins=10,palette='Paired',edgecolor='black',stat='frequency',kde=True)

sns.jointplot(data=df,x='total_bill',y='tip',hue='smoker',palette='Reds',kind='scatter')

sns.jointplot(data=df,x='total_bill',y='tip',hue='smoker',palette='bright',kind='kde')

sns.pairplot(data=df,hue='smoker',vars=['total_bill','size','tip'],kind='hist')

a = sns.countplot(data=df,x='day',palette='coolwarm',order = ['Sat','Sun','Thur','Fri'])
for i in a.containers:
  a.bar_label(i,color='black',label_type='edge',padding =10)

s = sns.barplot(data=df,x='day',y='total_bill',hue='sex',palette='Set3',estimator= 'mean',orient='v',errorbar=None)
for i in s.containers:
  s.bar_label(i,color='black',label_type='center',rotation=90)

d = sns.scatterplot(data=df,x='tip',y='total_bill',hue='sex',palette='Set1')

sns.swarmplot(data=df,x='day',y='total_bill',hue='smoker',palette='Greens',dodge=True)

sns.get_dataset_names()

df = sns.load_dataset('tips')

sns.boxplot(data=df,y='total_bill',hue='sex',palette='Greens')

q1 = df['total_bill'].quantile(0.25)
q3 = df['total_bill'].quantile(0.75)
iqr = q3-q1
iqr

lb = q1-1.5*iqr
ub = q3 + 1.5*iqr
lb,ub

#Identifying Outliers
df[(df['total_bill'] > ub) | (df['total_bill']<lb)]

# Removing Outliers
 df1 = df[(df['total_bill'] <ub) & (df['total_bill'] > lb)]

sns.boxplot(data=df1,y='total_bill',hue='sex',palette='Greens')

sns.kdeplot(data = df,x ='tip',hue='smoker',fill=True,palette='tab10')

sns.kdeplot(data = df1,x ='tip',fill=True,palette='tab20')

sns.violinplot(data=df,x='total_bill',hue='sex',palette='Set2')

sns.violinplot(data=df1,x='total_bill',hue='sex',palette='Set3')

sns.regplot(data=df,x='total_bill',y='tip')

sns.lmplot(data = df,x='total_bill',y='tip',palette='coolwarm',hue='sex',col='time',row='day')

